# -*- coding: utf-8 -*-
# Du lieu cho web demo: danh muc API day du + cac luu y quan trong tu dieu tra.
# Tach rieng de de bo sung ma khong dung vao code server.
#
# CATALOG: try=True -> GET an toan, web cho bam "Goi thu" ({key}/{project} thay bang input)

CATALOG = [
    {"group": "1. Trigger — Webhook (Jira chủ động gọi mình)", "items": [
        {"method": "POST", "path": "/rest/webhooks/1.0/webhook", "try": False,
         "name": "Đăng ký webhook (cần quyền admin)",
         "ai": "Điểm khởi đầu của cả flow: Jira tự báo khi ticket được tạo/sửa/comment, kèm JQL filter để chỉ nhận đúng project. Service KHÔNG cần polling.",
         "how": 'Body: {"name", "url", "events": ["jira:issue_created","jira:issue_updated","comment_created"], "filters": {"issue-related-events-section": "project = SCRUM"}}.'},
        {"method": "GET", "path": "/rest/webhooks/1.0/webhook", "try": True,
         "name": "Liệt kê webhook đã đăng ký",
         "ai": "Kiểm tra webhook đang trỏ về đâu, còn enabled không. DELETE vào URL self của từng webhook để gỡ.",
         "how": "Không tham số."},
        {"method": "POST", "path": "/rest/api/3/webhook", "try": False,
         "name": "Webhook động (chỉ cho OAuth/Connect app)",
         "ai": "Phương án webhook khi xây app phân phối chính thức. KHÔNG dùng được với API token.",
         "how": "Kèm GET /rest/api/3/webhook/failed (xem webhook gửi lỗi) và PUT /rest/api/3/webhook/refresh (gia hạn — webhook OAuth hết hạn sau 30 ngày)."},
    ]},
    {"group": "2. Đọc hiểu ticket (input chính cho AI)", "items": [
        {"method": "GET", "path": "/rest/api/3/issue/{key}?expand=renderedFields,names,changelog&fields=*all", "try": True,
         "name": "Get issue — API trung tâm",
         "ai": "Một call lấy gần hết: summary, description, status, priority, labels, custom fields, issue links, subtasks, attachment metadata, changelog. 'names' dịch customfield_xxxxx thành tên người hiểu được; 'renderedFields' trả HTML thay vì ADF.",
         "how": "Description mặc định là ADF (JSON) — cần converter sang text cho AI (xem adf_to_text trong jira_client.py)."},
        {"method": "GET", "path": "/rest/api/3/issue/{key}/comment?orderBy=created", "try": True,
         "name": "Get comments",
         "ai": "Thảo luận trong comment thường chứa nguyên nhân gốc và cách fix — phần giá trị nhất khi AI đọc ticket tương tự đã giải quyết.",
         "how": "Phân trang startAt/maxResults; body comment cũng là ADF. Ticket JSM có cờ jsdPublic phân biệt comment nội bộ/công khai."},
        {"method": "GET", "path": "/rest/api/3/issue/{key}/changelog", "try": True,
         "name": "Get changelog",
         "ai": "Lịch sử ai đổi gì khi nào — AI hiểu ticket đã đi qua những bước nào, bị trả lại bao nhiêu lần.",
         "how": "Hoặc gộp vào Get issue bằng expand=changelog. Đọc hàng loạt: POST /rest/api/3/changelog/bulkfetch."},
        {"method": "GET", "path": "/rest/api/3/attachment/content/{id}", "try": False,
         "name": "Tải nội dung attachment (đã test: khớp 100%)",
         "ai": "Đọc log lỗi, config đính kèm — GET issue chỉ trả metadata, muốn AI đọc nội dung file phải gọi endpoint này.",
         "how": "id từ fields.attachment[].id; response binary. Upload: POST /issue/{key}/attachments (multipart + header X-Atlassian-Token: no-check)."},
        {"method": "GET", "path": "/rest/api/3/attachment/thumbnail/{id}", "try": False,
         "name": "Thumbnail ảnh đính kèm",
         "ai": "Lấy bản thu nhỏ của screenshot khi không cần ảnh gốc (tiết kiệm băng thông/token vision).",
         "how": "Kèm GET /attachment/{id}/expand/human — xem danh sách file BÊN TRONG file zip mà không cần tải về."},
        {"method": "GET", "path": "/rest/api/3/issue/{key}/remotelink", "try": True,
         "name": "Get remote links",
         "ai": "Link ngoài gắn vào ticket (trang Confluence, PR...) — ngữ cảnh bổ sung.",
         "how": "Không tham số."},
        {"method": "GET", "path": "/rest/api/3/issue/{key}/worklog", "try": True,
         "name": "Get worklogs",
         "ai": "Ai đã làm bao nhiêu giờ trên ticket — tín hiệu về độ phức tạp thực tế và người hiểu ticket nhất.",
         "how": "Phân trang startAt/maxResults."},
        {"method": "GET", "path": "/rest/api/3/issue/{key}/watchers", "try": True,
         "name": "Get watchers",
         "ai": "Ai đang theo dõi ticket — tín hiệu mức độ quan tâm, ứng viên để hỏi thêm thông tin.",
         "how": "Kèm GET /issue/{key}/votes — số vote (mức độ mong muốn từ người dùng)."},
        {"method": "GET", "path": "/rest/api/3/issue/{key}/properties", "try": True,
         "name": "Đọc issue properties",
         "ai": "Đọc lại trạng thái AI đã lưu trên ticket (đã xử lý chưa, kết quả gì) — xem mục PUT properties ở nhóm 4.",
         "how": "GET .../properties liệt kê keys; GET .../properties/{propertyKey} đọc giá trị."},
        {"method": "POST", "path": "/rest/api/3/issue/bulkfetch", "try": False,
         "name": "Bulk fetch — lấy chi tiết hàng loạt",
         "ai": "Sau khi search ra danh sách key, lấy chi tiết tối đa 100 ticket/call thay vì gọi lẻ.",
         "how": 'Body: {"issueIdsOrKeys": ["SCRUM-5","SCRUM-6"], "fields": [...]}. Tương tự POST /comment/list đọc comment hàng loạt theo id.'},
        {"method": "POST", "path": "/rest/api/3/comment/list", "try": False,
         "name": "Đọc comment hàng loạt theo ID",
         "ai": "Khi đã có id của nhiều comment (vd từ nhiều ticket tương tự), lấy hết trong 1 call thay vì gọi lẻ từng ticket.",
         "how": 'Body: {"ids": [10000, 10001, ...]}.'},
        {"method": "POST", "path": "/rest/api/3/changelog/bulkfetch", "try": False,
         "name": "Đọc changelog hàng loạt",
         "ai": "Lấy lịch sử thay đổi của nhiều ticket cùng lúc — dựng bức tranh các ticket tương tự đã đi qua những bước nào.",
         "how": 'Body: {"issueIdsOrKeys": ["SCRUM-5","SCRUM-6"]}.'},
        {"method": "GET", "path": "/rest/api/3/field", "try": True,
         "name": "Danh mục toàn bộ field",
         "ai": "Bảng tra customfield_xxxxx → tên + kiểu dữ liệu. Cache 1 lần dùng mãi.",
         "how": "Với custom field dạng select: GET /field/{fieldId}/contexts rồi GET /field/{fieldId}/context/{contextId}/option để lấy danh sách giá trị hợp lệ."},
        {"method": "GET", "path": "/rest/api/3/field/{fieldId}/context", "try": False,
         "name": "Context của một custom field",
         "ai": "Bước trung gian để lấy danh sách giá trị hợp lệ của custom field dạng select/multi-select — cần khi AI muốn set custom field.",
         "how": "Lấy contextId ở đây rồi GET /field/{fieldId}/context/{contextId}/option. (Đừng dùng /contexts số nhiều — Atlassian đã deprecated.) fieldId vd customfield_10020."},
    ]},
    {"group": "3. Tìm ticket tương tự đã giải quyết", "items": [
        {"method": "GET", "path": '/rest/api/3/search/jql?jql=project = {project} AND statusCategory = Done AND text ~ "timeout"&fields=summary,status,resolution&maxResults=10', "try": True,
         "name": "Enhanced JQL search — endpoint hiện hành",
         "ai": "Trái tim của việc tìm ticket tương tự. JQL mẫu: statusCategory = Done AND (text ~ \"keywords\" OR labels in (...)). LƯU Ý: text ~ là keyword search (không semantic) và KHÔNG quét labels.",
         "how": "Endpoint /search cũ đã khai tử. JQL phải bounded (có project=...). Phân trang bằng nextPageToken (không còn startAt). reconcileIssues=[ids] nếu cần đọc-ngay-sau-ghi."},
        {"method": "POST", "path": "/rest/api/3/search/jql", "try": False,
         "name": "Enhanced JQL search — bản POST (code thật dùng bản này)",
         "ai": "Giống bản GET nhưng truyền JQL/fields trong body — bắt buộc khi JQL dài hoặc có ký tự đặc biệt. ai_context.py của service đang dùng đúng bản này.",
         "how": 'Body: {"jql": "...", "fields": [...], "maxResults": 50, "nextPageToken": "..."}.'},
        {"method": "GET", "path": "/rest/api/3/issue/picker?query=timeout", "try": True,
         "name": "Issue picker — gợi ý nhanh theo text",
         "ai": "Bước tìm ứng viên rẻ và nhanh trước khi search JQL đầy đủ. Trả 2 danh sách: lịch sử người dùng + kết quả khớp text.",
         "how": "query = chuỗi tự do; currentJQL để giới hạn phạm vi; currentProjectId lọc theo project."},
        {"method": "POST", "path": "/rest/api/3/search/approximate-count", "try": False,
         "name": "Đếm nhanh số kết quả",
         "ai": "Biết JQL trả khoảng bao nhiêu ticket trước khi fetch — quyết định có cần thu hẹp điều kiện không.",
         "how": 'Body: {"jql": "..."}. JQL phải bounded.'},
        {"method": "POST", "path": "/rest/api/3/jql/parse", "try": False,
         "name": "Validate JQL",
         "ai": "Nếu để AI tự sinh JQL: parse trước khi chạy, lỗi thì trả cho AI sửa — tránh request hỏng.",
         "how": 'Body: {"queries": ["project = SCRUM AND ..."]}.'},
        {"method": "POST", "path": "/rest/api/3/jql/match", "try": False,
         "name": "Kiểm tra issue khớp JQL",
         "ai": "Trả lời câu 'ticket X có thuộc diện Y không' mà không cần search lại toàn bộ.",
         "how": 'Body: {"jqls": [...], "issueIds": [...]}.'},
        {"method": "GET", "path": "/rest/api/3/jql/autocompletedata", "try": True,
         "name": "Danh mục field/operator JQL",
         "ai": "Đưa vào prompt làm tài liệu tham chiếu để AI sinh JQL đúng cú pháp, đúng tên field của site.",
         "how": "Cache 1 lần."},
    ]},
    {"group": "4. Phán đoán & hành động (AI quyết → service làm)", "items": [
        {"method": "GET", "path": "/rest/api/3/issue/{key}/transitions", "try": True,
         "name": "Các bước chuyển hợp lệ",
         "ai": "AI chỉ được đề xuất chuyển trạng thái trong danh sách này — workflow mỗi project khác nhau, không đoán được.",
         "how": "Lấy transition id ở đây rồi POST cùng đường dẫn để thực hiện."},
        {"method": "GET", "path": "/rest/api/3/issue/{key}/editmeta", "try": True,
         "name": "Field nào sửa được + giá trị hợp lệ",
         "ai": "Trước khi AI đề xuất sửa field: biết field đó có trên màn hình edit không, nhận giá trị gì — tránh đề xuất bất khả thi.",
         "how": "Không tham số."},
        {"method": "GET", "path": "/rest/api/3/issue/createmeta/{project}/issuetypes", "try": True,
         "name": "Metadata để TẠO ticket",
         "ai": "Chỉ cần nếu cho AI tạo ticket mới (vd tách bug, tạo subtask): liệt kê các issue type mà project cho phép tạo.",
         "how": "Đây là bước 1 (lấy issueTypeId). Bước 2: GET /issue/createmeta/{project}/issuetypes/{issueTypeId} để biết field nào bắt buộc của từng loại."},
        {"method": "GET", "path": "/rest/api/3/user/assignable/search?issueKey={key}", "try": True,
         "name": "Người được phép gán (đã test)",
         "ai": "AI đề xuất assignee phải nằm trong danh sách này, nếu không PUT assignee sẽ 400.",
         "how": "Trả accountId — Jira Cloud chỉ nhận accountId, không nhận username/email."},
        {"method": "GET", "path": "/rest/api/3/mypermissions?projectKey={project}&permissions=ASSIGN_ISSUES,TRANSITION_ISSUES,ADD_COMMENTS,EDIT_ISSUES", "try": True,
         "name": "Quyền của tài khoản bot (đã test)",
         "ai": "Service tự kiểm tra đủ quyền làm hành động AI đề xuất không, trước khi thử và thất bại.",
         "how": "permissions = danh sách permission key cách nhau dấu phẩy."},
        {"method": "GET", "path": "/rest/api/3/project/{project}/components", "try": True,
         "name": "Components + lead",
         "ai": "Mỗi component có 'lead' (người phụ trách) — nguồn cho quy ước 'bug component X → giao lead X'.",
         "how": "Kèm GET /component/{id}/relatedIssueCounts — component nào đang nhiều bug."},
        {"method": "GET", "path": "/rest/api/3/project/{project}/role", "try": True,
         "name": "Vai trò trong project",
         "ai": "Ai là Developer/Admin của project — gợi ý assignee theo vai trò.",
         "how": "Trả URL từng role, gọi tiếp để lấy thành viên."},
        {"method": "GET", "path": "/rest/api/3/groupuserpicker?query=hai", "try": True,
         "name": "Tìm người theo tên",
         "ai": "Resolve tên người được nhắc trong comment ('giao cho anh Nam') → accountId.",
         "how": "query = tên gần đúng."},
        {"method": "POST", "path": "/rest/api/3/issue/{key}/comment", "try": False,
         "name": "Ghi comment (hành động an toàn nhất — nên là mặc định)",
         "ai": "AI ghi kết quả phân tích + link ticket tương tự + gợi ý cách fix vào ticket.",
         "how": "Body comment phải là ADF."},
        {"method": "PUT", "path": "/rest/api/3/issue/{key}/assignee", "try": False,
         "name": "Gán người xử lý", "ai": "Thực thi đề xuất assignee của AI.",
         "how": 'Body: {"accountId": "..."}. Kiểm tra assignable trước (xem trên).'},
        {"method": "POST", "path": "/rest/api/3/issue/{key}/transitions", "try": False,
         "name": "Chuyển trạng thái", "ai": "Thực thi đề xuất chuyển workflow của AI.",
         "how": 'Body: {"transition": {"id": "41"}}. Response 204 RỖNG — client phải xử lý body rỗng (đã vấp khi test).'},
        {"method": "PUT", "path": "/rest/api/3/issue/{key}", "try": False,
         "name": "Sửa field (label, priority, component...)",
         "ai": "Thực thi đề xuất chỉnh field của AI.",
         "how": "Thêm ?notifyUsers=false để không spam email watcher. Body theo editmeta."},
        {"method": "POST", "path": "/rest/api/3/issue/{key}/notify", "try": False,
         "name": "Gửi thông báo đích danh",
         "ai": "Khi AI xác định cần người cụ thể chú ý (vd nghi trùng ticket đang mở của họ).",
         "how": 'Body: {"subject", "textBody", "to": {"users": [...]}}.'},
        {"method": "POST", "path": "/rest/api/3/issueLink", "try": False,
         "name": "Tạo link giữa 2 ticket",
         "ai": "AI phát hiện trùng/liên quan → tạo link 'duplicates'/'relates to' để người đọc thấy ngay.",
         "how": 'Body: {"type": {"name": "Duplicate"}, "inwardIssue": {"key"}, "outwardIssue": {"key"}}. Danh sách loại link: GET /issueLinkType.'},
        {"method": "PUT", "path": "/rest/api/3/issue/{key}/properties/ai-state", "try": False,
         "name": "Issue property — bộ nhớ ẩn của AI trên ticket",
         "ai": "Lưu 'ticket này AI xử lý chưa, kết quả gì' ngay trên ticket mà không làm bẩn field hiển thị → giải quyết webhook bắn trùng (idempotency).",
         "how": "PUT body JSON bất kỳ; GET cùng đường dẫn để đọc lại."},
    ]},
    {"group": "5. Danh mục ngữ cảnh (cache 1 lần khi khởi động)", "items": [
        {"method": "GET", "path": "/rest/api/3/myself", "try": True,
         "name": "Tài khoản đang đăng nhập", "ai": "Smoke test xác thực; lấy accountId của bot để lọc comment do chính bot viết (tránh AI tự đọc lại output của mình).", "how": ""},
        {"method": "GET", "path": "/rest/api/3/serverInfo", "try": True,
         "name": "Thông tin site", "ai": "Kiểm tra kết nối + xác nhận deploymentType=Cloud (API v3 chỉ có trên Cloud).", "how": "Gọi được không cần đăng nhập."},
        {"method": "GET", "path": "/rest/api/3/project/{project}", "try": True,
         "name": "Get project — chi tiết 1 project",
         "ai": "Lấy projectId (id số, cần cho vài API khác), lead, mô tả, loại project (software/JSM) làm ngữ cảnh.", "how": "Nhận projectKey hoặc projectId."},
        {"method": "GET", "path": "/rest/api/3/project/search", "try": True,
         "name": "Get projects — danh sách phân trang",
         "ai": "Liệt kê các project service được phép xử lý — hữu ích khi mở rộng ra nhiều project.", "how": "Phân trang startAt/maxResults; query để lọc theo tên/key."},
        {"method": "GET", "path": "/rest/api/3/priority", "try": True,
         "name": "Các mức priority", "ai": "AI đề xuất đổi priority phải dùng giá trị trong này.", "how": ""},
        {"method": "GET", "path": "/rest/api/3/resolution", "try": True,
         "name": "Các loại resolution", "ai": "Hiểu 'Fixed' khác 'Won't Fix' khi đọc ticket đã đóng.", "how": ""},
        {"method": "GET", "path": "/rest/api/3/project/{project}/statuses", "try": True,
         "name": "Workflow theo issue type của project", "ai": "Bug và Task có thể đi workflow khác nhau — AI cần biết trước khi đề xuất.", "how": "Toàn site: GET /statuses/search; nhóm trạng thái: GET /statuscategory."},
        {"method": "GET", "path": "/rest/api/3/label", "try": True,
         "name": "Toàn bộ labels", "ai": "AI gắn label nên chọn label có sẵn thay vì sinh mới tùy tiện.", "how": ""},
        {"method": "GET", "path": "/rest/api/3/project/{project}/versions", "try": True,
         "name": "Versions của project", "ai": "Ngữ cảnh affectedVersion/fixVersion khi AI đề xuất gắn bản phát hành.", "how": "Kèm GET /version/{id}/unresolvedIssueCount — version nào còn nhiều bug."},
        {"method": "GET", "path": "/rest/api/3/issuetype/project?projectId={projectId}", "try": False,
         "name": "Issue types của project", "ai": "AI phân loại ticket (Bug/Task/Story) theo đúng bộ loại của project.", "how": "projectId là id số (lấy từ GET /project/{key})."},
    ]},
    {"group": "6. Hai họ API ngoài Platform (cùng site, cùng auth, tài liệu riêng)", "items": [
        {"method": "GET", "path": "/rest/agile/1.0/board", "try": True,
         "name": "Agile API — boards",
         "ai": "Ngữ cảnh Scrum/Kanban: ticket thuộc board nào. Platform API chỉ lộ sprint qua customfield.",
         "how": "Họ /rest/agile/1.0/: board/{id}/sprint (sprint active), sprint/{id}/issue, epic... Tài liệu: developer.atlassian.com → Jira Software Cloud REST API."},
        {"method": "GET", "path": "/rest/agile/1.0/board/{boardId}/sprint?state=active", "try": False,
         "name": "Agile API — sprint đang chạy",
         "ai": "Ticket mới có thuộc sprint hiện tại không → mức độ khẩn cấp khác nhau.",
         "how": "boardId từ GET /rest/agile/1.0/board."},
        {"method": "GET", "path": "/rest/servicedeskapi/request/{key}", "try": False,
         "name": "JSM API — support request",
         "ai": "CHỈ cần khi ticket là support request của khách hàng (project JSM): SLA, request type, comment public/internal (cờ jsdPublic).",
         "how": "Site phải bật Jira Service Management. Với ticket software thuần thì bỏ qua nhóm này."},
    ]},
]

# ============ TAB LUU Y QUAN TRONG ============
# tag: "bẫy" (de vap) | "đã test" (kiem chung tren site that) | "khuyến nghị" (nen lam)
NOTES = [
    {"group": "Webhook", "items": [
        {"tag": "khuyến nghị", "title": "Webhook chỉ là trigger — luôn gọi lại GET issue",
         "text": "Payload event comment chỉ chứa issue rút gọn 6 fields (không có description). Payload issue_created/updated tuy đầy đủ nhưng có thể cũ nếu nhiều event đến gần nhau. Chỉ lấy issue.key + loại event từ payload, rồi GET /issue/{key} lấy dữ liệu tươi."},
        {"tag": "đã test", "title": "Thứ tự webhook KHÔNG đảm bảo",
         "text": "Quan sát thực tế: issue_updated đến TRƯỚC issue_created 1 giây, comment_created đến muộn hơn 4 giây. Service không được giả định thứ tự — thêm một lý do để chỉ dùng webhook làm trigger."},
        {"tag": "bẫy", "title": "Description trong payload webhook là text thuần, không phải ADF",
         "text": "REST API v3 trả description/comment dạng ADF (JSON), nhưng payload webhook lại trả text thuần kiểu v2. Parser phải xử lý cả hai định dạng. Chỉ phát hiện được khi bắt payload thật."},
        {"tag": "bẫy", "title": "Webhook của OAuth app hết hạn sau 30 ngày",
         "text": "Webhook đăng ký qua /rest/api/3/webhook (OAuth/Connect app) phải gọi PUT /webhook/refresh định kỳ. Webhook admin (/rest/webhooks/1.0/webhook) không hết hạn nhưng cần quyền admin để đăng ký."},
        {"tag": "đã test", "title": "JQL filter khi đăng ký hoạt động đúng",
         "text": "Đăng ký kèm filters.issue-related-events-section = \"project = SCRUM\" → chỉ ticket project đó bắn event. Độ trễ thực tế ~1 giây. Lọc ngay từ nguồn, đỡ xử lý rác."},
        {"tag": "bẫy", "title": "Giới hạn vận hành của webhook",
         "text": "Payload >25MB không gửi. Gửi lỗi sẽ retry tối đa 5 lần (cách 5–15 phút) — service nhận webhook PHẢI idempotent vì có thể nhận trùng. Tối đa 20 request đồng thời mỗi cặp tenant/URL."},
    ]},
    {"group": "Đọc dữ liệu & ADF", "items": [
        {"tag": "khuyến nghị", "title": "3 expand đáng giá nhất khi GET issue",
         "text": "expand=renderedFields (HTML thay vì ADF — AI đọc dễ hơn), names (dịch customfield_10020 → 'Sprint'), changelog (lịch sử kèm luôn, đỡ 1 call)."},
        {"tag": "đã test", "title": "Attachment: GET issue chỉ trả metadata",
         "text": "Muốn đọc nội dung file (log, config) phải GET /attachment/content/{id} — đã test upload error.log rồi tải về khớp 100%. Upload cần multipart + header X-Atlassian-Token: no-check."},
        {"tag": "bẫy", "title": "Response 204 body rỗng",
         "text": "Một số API ghi (POST transitions, PUT assignee...) trả 204 No Content. Client parse JSON mù quáng sẽ crash — đã vấp khi test."},
        {"tag": "khuyến nghị", "title": "Lọc comment của chính bot",
         "text": "Khi AI ghi comment vào ticket, các lần đọc sau phải lọc bỏ comment do accountId của bot viết (lấy accountId qua GET /myself) — tránh AI đọc lại và khuếch đại output của chính mình."},
    ]},
    {"group": "Tìm kiếm & JQL", "items": [
        {"tag": "bẫy", "title": "Endpoint /search cũ đã khai tử",
         "text": "Chỉ dùng GET|POST /rest/api/3/search/jql. Khác biệt: JQL bắt buộc bounded (phải có project=... hoặc điều kiện giới hạn), phân trang bằng nextPageToken (không còn startAt/total). Swagger của Atlassian tự đánh dấu /search là 'Currently being removed'."},
        {"tag": "bẫy", "title": "text ~ KHÔNG quét labels",
         "text": "Lần test đầu ra 0 kết quả vì keyword nằm trong label. JQL tìm tương tự nên là: (text ~ \"keywords\" OR labels in (label1, label2))."},
        {"tag": "bẫy", "title": "Jira KHÔNG có semantic search",
         "text": "text ~ là keyword matching (Lucene). Flow khuyến nghị: AI trích keywords → search lấy ~20 ứng viên → bulkfetch chi tiết → AI re-rank. Nếu chất lượng không đủ trên dữ liệu thật → tự xây vector DB (việc của AI team, ngoài phạm vi Jira API)."},
        {"tag": "đã test", "title": "Tiếng Việt không dấu tìm được bình thường",
         "text": "text ~ \"thanh toan\" khớp description chứa 'thanh toan'. Dữ liệu thật viết CÓ DẤU thì cần test thêm trường hợp có dấu/không dấu lẫn lộn."},
        {"tag": "khuyến nghị", "title": "AI sinh JQL thì validate trước",
         "text": "POST /jql/parse để bắt lỗi cú pháp trước khi chạy; GET /jql/autocompletedata đưa vào prompt làm tài liệu field/operator chuẩn của site."},
        {"tag": "khuyến nghị", "title": "Đọc-ngay-sau-ghi dùng reconcileIssues",
         "text": "Search index có độ trễ — vừa sửa ticket xong mà search ngay có thể chưa thấy. Truyền reconcileIssues=[issueId] (tối đa 50) để ép consistency."},
    ]},
    {"group": "Hành động & quyền", "items": [
        {"tag": "đã test", "title": "3 bước kiểm tra TRƯỚC khi AI hành động",
         "text": "1) GET /issue/{key}/transitions — chỉ chuyển được trạng thái trong danh sách này; 2) GET /user/assignable/search?issueKey= — chỉ gán được người trong danh sách này (sai → 400); 3) GET /mypermissions — bot đủ quyền chưa. Cả 3 đã test OK trên site thật."},
        {"tag": "khuyến nghị", "title": "Hành động mặc định nên là comment",
         "text": "Trong các hành động (comment/assign/transition/edit), comment an toàn nhất — không phá workflow, người thật vẫn toàn quyền. Nên để AI ghi phân tích + link ticket tương tự dạng comment, các hành động mạnh hơn cần người duyệt."},
        {"tag": "bẫy", "title": "Jira Cloud chỉ nhận accountId",
         "text": "Mọi API liên quan đến người (assignee, mention...) dùng accountId, KHÔNG nhận username/email (đã bị xóa vì GDPR). Resolve tên → accountId bằng GET /groupuserpicker?query=."},
        {"tag": "khuyến nghị", "title": "notifyUsers=false khi sửa hàng loạt",
         "text": "PUT /issue/{key}?notifyUsers=false để không spam email watcher mỗi lần AI chỉnh field."},
        {"tag": "khuyến nghị", "title": "Idempotency bằng issue properties",
         "text": "Webhook có thể bắn trùng (retry). Lưu PUT /issue/{key}/properties/ai-state = {processed_at, result} — lần sau nhận event cùng ticket thì đọc property này để biết đã xử lý chưa."},
    ]},
    {"group": "Xác thực & giới hạn", "items": [
        {"tag": "đã test", "title": "Basic auth = email + API token",
         "text": "Token tạo tại id.atlassian.com/manage-profile/security/api-tokens, đi kèm ĐÚNG email của tài khoản tạo nó (sai email → 401). Token = toàn quyền tài khoản: không commit, không hardcode, revoke khi xong việc."},
        {"tag": "khuyến nghị", "title": "Production nên dùng tài khoản bot riêng",
         "text": "Tạo tài khoản service riêng (vd ai-bot@company.com) chỉ cấp quyền cần thiết trên project cần thiết — không dùng token cá nhân của dev. App phân phối rộng thì chuyển OAuth 2.0 (scopes read:jira-work, write:jira-work)."},
        {"tag": "bẫy", "title": "Rate limit theo cost-budget",
         "text": "Jira Cloud giới hạn theo chi phí request mỗi tenant. Gặp 429 phải đọc header Retry-After và backoff — service nhận webhook lúc cao điểm có thể bắn rất nhiều GET issue, nên có queue + cache."},
        {"tag": "bẫy", "title": "API v3 chỉ có trên Jira CLOUD",
         "text": "Site dạng *.atlassian.net là Cloud. Jira Server/Data Center tự host chỉ có v2 (/rest/api/2/), không ADF, webhook đăng ký khác — toàn bộ tài liệu này phải điều chỉnh nếu khách dùng bản tự host."},
    ]},
    {"group": "Kiến trúc service đề xuất", "items": [
        {"tag": "khuyến nghị", "title": "Flow chuẩn từ webhook đến hành động",
         "text": "Webhook (JQL filter) → GET /issue/{key}?expand=renderedFields,names,changelog → GET /issue/{key}/comment → [tải attachment nếu cần] → AI trích keywords → POST /search/jql (statusCategory=Done) → bulkfetch ứng viên → AI đọc cách giải quyết + phán đoán → hành động (comment/assign/transition) trong phạm vi transitions + assignable + permissions."},
        {"tag": "khuyến nghị", "title": "Cache các danh mục ít đổi",
         "text": "GET /field, /priority, /resolution, /project/{key}/statuses, /jql/autocompletedata — cache khi khởi động, refresh theo ngày. Giảm đáng kể số call và độ trễ build context."},
        {"tag": "khuyến nghị", "title": "Contract với AI team",
         "text": "Input = JSON context (xem ai_context.py + tab Demo): ticket normalize + similar_resolved kèm comment chứa cách fix + allowed_actions. Output AI = action có cấu trúc (loại hành động + tham số) nằm trong allowed_actions. Mọi format ADF/customfield đã được service xử lý trước — AI chỉ thấy text sạch."},
        {"tag": "đã test", "title": "Số liệu thực tế khi build context",
         "text": "1 ticket + 2 ticket tương tự + hành động khả dụng = 9 API call ≈ 4 giây (tuần tự). Production nên gọi song song các call độc lập → rút xuống ~1.5 giây."},
    ]},
]
